version: '3.1'
services:
  db:
    image: postgres:13.1
    privileged: true
    ports:
      - 5432:5432
    environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: 12345qwe
        POSTGRES_DB: db

  backend:
    build: ./todo
    privileged: true
    ports:
      - 8080:8080
    command:
      bash -c "
      ./wait-for-postgres.sh db
      python3 manage.py migrate &&
      python3 manage.py create_users 10 &&
      python3 manage.py create_data_project_and_todo 10 &&
      gunicorn todo.wsgi -b 0.0.0.0:8080
      "
    depends_on:
      - db

  nginx:
    build: ./ngnix
    ports:
      - 8001:80
    depends_on:
      - backend

  frontend:
    build: ./frontend
    ports:
      - 8002:80
    depends_on:
      - nginx