# Generated by Django 4.0.2 on 2022-02-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='url_repo',
            new_name='repository',
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название проекта'),
        ),
    ]
