# Generated by Django 4.0.2 on 2022-02-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_rename_is_active_todo_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание проекта'),
        ),
    ]
